// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aicaevwnvehlofhnkkda.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFpY2FldndudmVobG9maG5ra2RhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgzNjkyNTQsImV4cCI6MjA3Mzk0NTI1NH0.XXqHFrMiCcEK1aVHu2bJlhrK_EvqMInp-FfrgqQPmkk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});